# Generated by Django 4.2.10 on 2025-12-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('breaking', 'Breaking'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved')], default='breaking', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.category'),
        ),
    ]
