# Generated by Django 4.2.10 on 2025-12-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_category_incident_status_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('active', 'Breaking'), ('published', 'Confirmed'), ('inactive', 'Resolved')], default='Active', max_length=20),
        ),
    ]
